# fly.toml app configuration file generated for wallet-fiber on 2023-09-10T17:21:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wallet-fiber"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
